// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/FigureRecipe.cs - edit it there.
#nullable disable
using System.Security.Cryptography;
using global::CUE4Parse.FileProvider;
using global::CUE4Parse.UE4.Assets.Exports.Animation;
using global::CUE4Parse.UE4.Assets.Exports.Material;
using global::CUE4Parse.UE4.Assets.Exports.Texture;
using global::CUE4Parse_Conversion.Textures;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.Exporting.MaterialPorter;

/// <summary>
/// A LEGO figure that exists only as a recipe: its CustomizableObjectInstance
/// ("COI_Figure_X_Dataless") on the shared Mutable object CO_Figure_Recipe_Dataless.
/// That program builds only the body's geometry; the game dresses it from the
/// recipe's values, and so is it done here:
///  - the body: the program's standard body mesh (a streamed constant), with
///    MI_Figure_DecoratedPlastic_RecipeCOv2 (or the variant a "Body Material Type"
///    names), its "Tex Color D" a 32x32 grid of the body's layout blocks (layout 11 of
///    the program), each block the LUT colour of its part's "&lt;part&gt; Color" id
///    (T_LUT_Default, 512 x 1: pixel N is colour id N), deco and normal from the recipe;
///  - the head: the recipe's head mesh with its "Head Material", its base colour grid
///    ("Tex Color-D") the LUT colour of the face material's "Color Head ID";
///  - each accessory or replacement part ("&lt;X&gt; SKM"): its mesh with the recipe
///    material, a 2x2 colour grid ("LU/RU/LL/RL Color &lt;X&gt;": the quadrants
///    top left, top right, bottom left, bottom right) and its deco, mask and normal.
/// All parts are skinned to SK_Figure. Not done yet: the body parts a replacement
/// removes (hands and legs, a few dozen recipes), the skeleton body's own colour
/// layout, cloth, per-part surfaces (metal, glow).
/// </summary>
public sealed class FigureRecipe
{
    public const string LutPath = "/JunoBase/EditorUtility/LUT_Generator/Variants/T_LUT_Default.T_LUT_Default";
    public const string SkeletonPath = "/FigureCharacter/Figure_Core/SkeletalMesh/SK_Figure.SK_Figure";
    const string MaterialFolder = "/FigureCharacter/Figure_Core/Material/MaterialInstance/";
    const string RecipeMaterial = MaterialFolder + "MI_Figure_DecoratedPlastic_RecipeCOv2.MI_Figure_DecoratedPlastic_RecipeCOv2";
    /// <summary>The program's bodies at LOD 0 by "Body Selector": the standard one, the skeleton.</summary>
    const int BodyConstant = 4, SkeletonBodyConstant = 13;

    /// <summary>Generated textures' paths and folder (the app's MaterialService.GeneratedDir, which serves them).</summary>
    public const string GeneratedRoot = "/MaterialPorter/Generated/";
    public static string? GeneratedDir { get; set; }

    /// <summary>The body's colour layout: each part's block on the 32x32 grid (layout 11 of the program, matched to the parts by their bones).</summary>
    public static readonly (string Part, int X, int Y, int W, int H)[] BodyBlocks =
    [
        ("leg_lu", 20, 21, 12, 7), ("leg_ru", 20, 14, 12, 7), ("hand_l", 0, 18, 10, 4), ("torso", 20, 0, 12, 14),
        ("hand_r", 0, 28, 10, 4), ("hips", 0, 0, 10, 12), ("leg_rl", 10, 10, 10, 10), ("leg_ll", 10, 20, 10, 10),
        ("arm_ru", 0, 12, 4, 6), ("arm_lu", 0, 22, 4, 6), ("arm_rl", 4, 12, 5, 6), ("arm_ll", 4, 22, 5, 6),
    ];

    public string Instance { get; private init; } = "";
    public string CustomizableObject { get; private init; } = "";
    public Dictionary<string, string> Ints { get; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, double> Floats { get; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, string> Textures { get; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, string> Meshes { get; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, string> Materials { get; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>A part of the figure to export.</summary>
    public sealed class Part
    {
        public string Name { get; init; } = "";
        /// <summary>A cooked skeletal mesh's path; null for the body (<see cref="Raw"/>).</summary>
        public string? Mesh { get; init; }
        public RawSkinnedMesh? Raw { get; init; }
        /// <summary>The body's name, the same for every figure with that body (its file is shared).</summary>
        public string RawName { get; init; } = "";
        /// <summary>The material for all its slots, or null: the mesh's own.</summary>
        public string? Material { get; init; }
        public Dictionary<string, string> Textures { get; } = new(StringComparer.OrdinalIgnoreCase);
        public Dictionary<string, double> Scalars { get; } = new(StringComparer.OrdinalIgnoreCase);
    }

    static readonly JsonSerializerSettings Ser = new() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

    /// <summary>A recipe from its instance's path (a CustomizableObjectInstance), or null.</summary>
    public static async Task<FigureRecipe?> LoadAsync(IFileProvider provider, string instancePath)
    {
        var package = instancePath.Contains('.') ? instancePath[..instancePath.LastIndexOf('.')] : instancePath;
        var pkg = await provider.LoadPackageAsync(package);
        var coi = pkg.GetExports().FirstOrDefault(e => e.ExportType == "CustomizableObjectInstance");
        if (coi is null) return null;
        var desc = JObject.Parse(JsonConvert.SerializeObject(coi, Ser))["Properties"]?["Descriptor"];
        if (desc is null) return null;
        var recipe = new FigureRecipe { Instance = instancePath, CustomizableObject = ObjectPath(desc["CustomizableObject"]) ?? "" };
        foreach (var x in desc["IntParameters"] ?? new JArray())
            if ((string?)x["ParameterName"] is { } n && (string?)x["ParameterValueName"] is { } v) recipe.Ints[n] = v;
        foreach (var x in desc["FloatParameters"] ?? new JArray())
            if ((string?)x["ParameterName"] is { } n && x["ParameterValue"] is { Type: JTokenType.Float or JTokenType.Integer } v) recipe.Floats[n] = (double)v;
        void Objects(string key, Dictionary<string, string> into)
        {
            foreach (var x in desc[key] ?? new JArray())
                if ((string?)x["ParameterName"] is { } n && ObjectPath(x["ParameterValue"]) is { } p) into[n] = p;
        }
        Objects("TextureParameters", recipe.Textures);
        Objects("SkeletalMeshParameters", recipe.Meshes);
        Objects("MaterialParameters", recipe.Materials);
        return recipe;
    }

    /// <summary>A serialized object reference ({ObjectName: "Class'Name'", ObjectPath: "/Pkg/Name.0"}) as "/Pkg/Name.Name".</summary>
    static string? ObjectPath(JToken? token)
    {
        if (token is not JObject o || (string?)o["ObjectPath"] is not { Length: > 0 } path || (string?)o["ObjectName"] is not { } name) return null;
        var q = name.IndexOf('\'');
        if (q >= 0) name = name[(q + 1)..].TrimEnd('\'');
        var dot = path.LastIndexOf('.');
        return (dot > path.LastIndexOf('/') ? path[..dot] : path) + "." + name.Split(':')[^1];
    }

    // ------------------------------------------------------------ shared data (once per game)

    static readonly SemaphoreSlim Gate = new(1, 1);
    static IFileProvider? _provider;
    static byte[]? _lut;
    static readonly Dictionary<int, RawSkinnedMesh> _bodies = new();
    static USkeleton? _skeleton;

    public static async Task<USkeleton> SkeletonAsync(IFileProvider provider)
    {
        await Shared(provider, null);
        return _skeleton!;
    }

    static async Task Shared(IFileProvider provider, string? customizableObject, int body = BodyConstant)
    {
        await Gate.WaitAsync();
        try
        {
            if (!ReferenceEquals(_provider, provider)) { _provider = provider; _lut = null; _bodies.Clear(); _skeleton = null; }
            _skeleton ??= await provider.LoadPackageObjectAsync<USkeleton>(SkeletonPath);
            if (_lut is null)
            {
                var lut = (await provider.LoadPackageObjectAsync<UTexture2D>(LutPath)).Decode(ETexturePlatform.DesktopMobile)
                          ?? throw new InvalidDataException("the LEGO colour LUT doesn't decode");
                var rgba = new byte[lut.Width * 4];
                var bgra = lut.PixelFormat == global::CUE4Parse.UE4.Assets.Exports.Texture.EPixelFormat.PF_B8G8R8A8;
                for (var x = 0; x < lut.Width; x++)
                {
                    rgba[x * 4] = lut.Data[x * 4 + (bgra ? 2 : 0)];
                    rgba[x * 4 + 1] = lut.Data[x * 4 + 1];
                    rgba[x * 4 + 2] = lut.Data[x * 4 + (bgra ? 0 : 2)];
                    rgba[x * 4 + 3] = lut.Data[x * 4 + 3];
                }
                _lut = rgba;
            }
            if (customizableObject is not null && !_bodies.ContainsKey(body))
            {
                var program = await MutableMeshes.LoadAsync(provider, customizableObject.Split('.')[0]);
                var bones = _skeleton.ReferenceSkeleton.FinalRefBoneInfo.Select(b => b.Name.Text).ToList();
                _bodies[body] = program.Skinned(body, bones) ?? throw new InvalidDataException("the figure body didn't decode");
            }
        }
        finally { Gate.Release(); }
    }

    /// <summary>A LEGO colour id's sRGB colour (the LUT's pixel), opaque.</summary>
    static byte[] Colour(double id)
    {
        var i = Math.Clamp((int)Math.Round(id), 0, _lut!.Length / 4 - 1);
        return [_lut[i * 4], _lut[i * 4 + 1], _lut[i * 4 + 2], 255];
    }

    // ------------------------------------------------------------ the figure

    /// <summary>The figure's parts, the body first. Writes its colour grids to <see cref="GeneratedDir"/>.</summary>
    public async Task<List<Part>> PartsAsync(IFileProvider provider)
    {
        var bodyConstant = Ints.GetValueOrDefault("Body Selector") is "Skeleton" ? SkeletonBodyConstant : BodyConstant;
        await Shared(provider, CustomizableObject, bodyConstant);
        var parts = new List<Part>();

        // the body: layout blocks in their parts' colours
        var body = new Part { Name = "Body", Raw = _bodies[bodyConstant], RawName = bodyConstant == BodyConstant ? "FigureBody" : "FigureBodySkeleton", Material = MaterialFor(provider, Ints.GetValueOrDefault("Body Material Type")) };
        var blocks = BodyBlocks.Select(b => (b.X, b.Y, b.W, b.H, Colour(Floats.GetValueOrDefault(b.Part + " Color", 1))));
        body.Textures["Tex Color D"] = Grid("FigureBody", blocks);
        Copy(body, "Body Deco D", "Tex Deco D");
        Copy(body, "Body Deco M", "Tex Deco M");
        Copy(body, "Body Normal", "Tex Normal");
        Copy(body, "Body Color M", "Tex Color M");
        if (Floats.TryGetValue("Body Metallic Power Deco", out var metal)) body.Scalars["Metallic Power Deco"] = metal;
        if (Floats.TryGetValue("Body Emissive Mult", out var em)) body.Scalars["Emissive Mult"] = em;
        if (Floats.TryGetValue("Body Element Emissive Mult", out var eem)) body.Scalars["Element Emissive Mult"] = eem;
        parts.Add(body);

        // the head: its face material, its base colour (a grid the game fills) the head's colour id:
        // the face material's "Color Head ID", else the recipe's "Head Standard Color" (ColorID_24_...)
        if (Meshes.TryGetValue("Head SKM", out var head))
        {
            var face = Materials.GetValueOrDefault("Head Material");
            var headPart = new Part { Name = "Head", Mesh = head, Material = face };
            var id = (face is null ? null : await ScalarAsync(provider, face, "Color Head ID"))
                     ?? (Ints.GetValueOrDefault("Head Standard Color") is { } std && std.Split('_') is { Length: > 1 } bits && int.TryParse(bits[1], out var n) ? n : 24);
            headPart.Textures["Tex Color-D"] = Grid("FigureHead", [(0, 0, 32, 32, Colour(id))]);
            parts.Add(headPart);
        }

        // accessories and replacement parts, each where its mode switch has it (Extend: the recipe's
        // material and colours; Override: its own override material)
        foreach (var (param, mesh) in Meshes)
        {
            if (!param.EndsWith(" SKM", StringComparison.OrdinalIgnoreCase) || param.Equals("Head SKM", StringComparison.OrdinalIgnoreCase)) continue;
            var x = param[..^4];
            var mode = Ints.GetValueOrDefault(ModeParameter(x)) ?? "None";
            if (mode.Equals("None", StringComparison.OrdinalIgnoreCase)) continue;
            if (x.Equals("Cape", StringComparison.OrdinalIgnoreCase) || x.Equals("NeckCloth", StringComparison.OrdinalIgnoreCase))
            {
                parts.Add(new Part { Name = x, Mesh = mesh, Material = Materials.GetValueOrDefault(x + " Material") });
                continue;
            }
            var material = mode.EndsWith("Override", StringComparison.OrdinalIgnoreCase) && Materials.TryGetValue(x + " Override Material", out var own)
                ? own : MaterialFor(provider, Ints.GetValueOrDefault(x + " Material"));
            var part = new Part { Name = x, Mesh = mesh, Material = material };
            // quadrants: top left, top right, bottom left, bottom right
            var quads = new[] { ("LU", 0, 0), ("RU", 16, 0), ("LL", 0, 16), ("RL", 16, 16) }
                .Select(q => (q.Item2, q.Item3, 16, 16, Colour(Floats.GetValueOrDefault($"{q.Item1} Color {x}", 1))));
            part.Textures["Tex Color D"] = Grid("FigurePart", quads);
            Copy(part, x + " Deco D", "Tex Deco D");
            Copy(part, x + " Deco Mask", "Tex Deco M");
            Copy(part, x + " Normal", "Tex Normal");
            if (Floats.TryGetValue(x + " EmissiveMult", out var pem)) part.Scalars["Emissive Mult"] = pem;
            if (Floats.TryGetValue(x + " ElementEmissiveMult", out var peem)) part.Scalars["Element Emissive Mult"] = peem;
            parts.Add(part);
        }
        return parts;
    }

    /// <summary>A material instance's scalar parameter, from it or the nearest parent instance that sets it.</summary>
    static async Task<double?> ScalarAsync(IFileProvider provider, string material, string name)
    {
        try
        {
            var mi = await provider.LoadPackageObjectAsync<UMaterialInstanceConstant>(material);
            for (var depth = 0; mi is not null && depth < 16; depth++)
            {
                foreach (var p in mi.ScalarParameterValues)
                    if (p.ParameterInfo.Name.Text.Equals(name, StringComparison.OrdinalIgnoreCase)) return p.ParameterValue;
                mi = mi.Parent as UMaterialInstanceConstant;
            }
        }
        catch
        {
            // a material that doesn't load: the fallback
        }
        return null;
    }

    /// <summary>The int parameter that turns a part on ("None", "... Extend", "... Override", "... ON").</summary>
    static string ModeParameter(string part) => part switch
    {
        "Head Acc" => "Head Accessory",
        "Head Acc Extra" => "Head Accessory Extra",
        "Neck Acc" => "Neck Accessory",
        "Neck Acc Extra" => "Neck Accessory Extra",
        "Hip Acc" => "Hip Accessory",
        "Cape" => "Cape",
        "NeckCloth" => "NeckCloth",
        _ => part + " Replacement",     // Hand L, Hand R, Leg L, Leg R
    };

    void Copy(Part part, string from, string to)
    {
        if (Textures.TryGetValue(from, out var path)) part.Textures[to] = path;
    }

    /// <summary>The plastic material a "... Material Type" value names: Default is the recipe's own.</summary>
    static string MaterialFor(IFileProvider provider, string? type)
    {
        if (string.IsNullOrEmpty(type) || type.Equals("Default", StringComparison.OrdinalIgnoreCase)) return RecipeMaterial;
        var name = "MI_Figure_DecoratedPlastic_" + type.Replace(" ", "").Replace("_", "");
        var path = MaterialFolder + name;
        return provider.TryGetGameFile(path + ".uasset", out _) ? path + "." + name : RecipeMaterial;
    }

    /// <summary>
    /// A 32x32 colour grid of blocks (x, y, w, h in pixels), written as a PNG 8 times
    /// the size (the game samples it unfiltered: the blocks stay sharp when Blender
    /// filters it). Returns its generated texture path.
    /// </summary>
    static string Grid(string kind, IEnumerable<(int X, int Y, int W, int H, byte[] Rgba)> blocks)
    {
        const int size = 32, scale = 8;
        var px = new byte[size * size * 4];
        foreach (var (x0, y0, w, h, c) in blocks)
            for (var y = y0; y < Math.Min(size, y0 + h); y++)
            for (var x = x0; x < Math.Min(size, x0 + w); x++)
                Array.Copy(c, 0, px, (y * size + x) * 4, 4);
        var name = kind + "_" + Convert.ToHexString(SHA1.HashData(px))[..12];
        var dir = GeneratedDir ?? throw new InvalidOperationException("FigureRecipe.GeneratedDir isn't set");
        var file = Path.Combine(dir, name + ".png");
        if (!File.Exists(file))
        {
            using var bitmap = new SkiaSharp.SKBitmap(size * scale, size * scale, SkiaSharp.SKColorType.Rgba8888, SkiaSharp.SKAlphaType.Unpremul);
            for (var y = 0; y < size * scale; y++)
            for (var x = 0; x < size * scale; x++)
            {
                var o = ((y / scale) * size + x / scale) * 4;
                bitmap.SetPixel(x, y, new SkiaSharp.SKColor(px[o], px[o + 1], px[o + 2], px[o + 3]));
            }
            using var png = bitmap.Encode(SkiaSharp.SKEncodedImageFormat.Png, 100);
            File.WriteAllBytes(file, png.ToArray());
        }
        return GeneratedRoot + name + "." + name;
    }
}
