// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/Mutable.cs - edit it there.
#nullable disable
using System.Reflection;
using global::CUE4Parse.FileProvider;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.Exporting.MaterialPorter;

/// <summary>
/// A cooked Mutable program (a CustomizableObject's Model.Program), run far
/// enough to say what each surface's material gets: the instance tree walked
/// under a set of parameter values, each surface's material op resolved, its
/// colour and scalar parameters evaluated. Meshes and images aren't built
/// (the items name the meshes; textures stay the materials' own).
///
/// The format, as read off Rocket Racing's CO_VehicleCosmeticsRoot (CUE4Parse
/// keeps the bytecode but not the op table): a reference is
/// (data type &lt;&lt; 24) | byte offset; an op is its type byte, then its
/// arguments. A switch is (variable, default, count, (value, ref)*); a
/// conditional (bool, yes, no).
///   bool   3 int == const   4 and   5 or   6 not
///   int    8 parameter
///   scalar 11 constant   12 parameter   13 conditional   14 switch
///   colour 19 constant (RGBA; NaN = leave the material's own)   20 parameter   21 conditional   22 switch
///   instance 116 conditional   117 switch   118 add (base, child, id)   119 component mesh
///            121 surface (previous, material, name id)   122 surface (previous, material, string index)
///   material 130 constant (_, passthrough id)   131 parameter   132 conditional   133 switch
///            134/135 a mesh's own slot (name id, mesh)
///            137 parameters (base, count, (name id, flag, ref [+4 for images])*)
/// </summary>
public sealed class MutableProgram
{
    public sealed class Param
    {
        public string Name { get; init; }
        public string Type { get; init; }
        public JToken Default { get; init; }
        public Dictionary<string, int> Values { get; } = new(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>What a surface's material came to.</summary>
    public sealed class Surface
    {
        public string Name { get; init; }
        /// <summary>The material: a mesh's own slot (by name), a material parameter, or an asset.</summary>
        public string Slot { get; set; }
        public string MaterialParam { get; set; }
        public string Asset { get; set; }
        public Dictionary<string, double[]> Vectors { get; } = new(StringComparer.OrdinalIgnoreCase);
        public Dictionary<string, double> Scalars { get; } = new(StringComparer.OrdinalIgnoreCase);
    }

    byte[] code;
    uint root;
    readonly List<Param> parameters = new();
    readonly Dictionary<string, int> index = new(StringComparer.OrdinalIgnoreCase);
    readonly Dictionary<uint, string> names = new();
    string[] strings = Array.Empty<string>();
    readonly Dictionary<uint, string> passthrough = new();

    public IReadOnlyList<Param> Parameters => parameters;
    public bool Has(string name) => index.ContainsKey(name);
    public Param Get(string name) => index.TryGetValue(name, out var i) ? parameters[i] : null;

    static readonly JsonSerializerSettings Ser = new() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };
    static JToken Json(object o) => JToken.Parse(JsonConvert.SerializeObject(o, Ser));

    static object Member(object o, string name)
    {
        const BindingFlags F = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;
        var t = o.GetType();
        return t.GetField(name, F)?.GetValue(o) ?? t.GetProperty(name, F)?.GetValue(o);
    }

    public static async Task<MutableProgram> LoadAsync(IFileProvider provider, string coPackage)
    {
        var pkg = await provider.LoadPackageAsync(coPackage);
        var exports = pkg.GetExports().ToList();
        var co = exports.First(e => e.ExportType == "CustomizableObject");
        var program = Member(Member(co, "Model"), "Program");
        var p = new MutableProgram
        {
            code = (byte[])Member(program, "ByteCode"),
            strings = (string[])Member(program, "ConstantStrings") ?? Array.Empty<string>(),
        };
        var states = Json(Member(program, "States"));
        p.root = (uint)states[0]!["Root"]!;
        foreach (var d in Json(Member(program, "Parameters")))
        {
            var par = new Param { Name = (string)d["Name"], Type = (string)d["Type"], Default = d["DefaultValue"] };
            foreach (var v in d["PossibleValues"] ?? new JArray())
                par.Values[(string)v["Name"] ?? ""] = (int)v["Value"];
            p.index[par.Name] = p.parameters.Count;
            p.parameters.Add(par);
        }
        foreach (var kv in (JObject)Json(Member(program, "ConstantNames")))
            p.names[uint.Parse(kv.Key)] = (string)kv.Value;
        var res = exports.FirstOrDefault(e => e.ExportType == "ModelResources" && e.Name.EndsWith("WindowsClient"))
                  ?? exports.FirstOrDefault(e => e.ExportType == "ModelResources");
        if (res != null)
            foreach (var x in Json(res)["Properties"]?["PassthroughObjects"] ?? new JArray())
                if (uint.TryParse((string)x["Key"], out var k)) p.passthrough[k] = (string)x["Value"]?["AssetPathName"];
        return p;
    }

    public int? EnumValue(string param, string name) =>
        Get(param) is { } par && name != null && par.Values.TryGetValue(name, out var v) ? v : null;

    // ------------------------------------------------------------ evaluation
    uint U(int o) => BitConverter.ToUInt32(code, o);
    int I(int o) => BitConverter.ToInt32(code, o);
    float F(int o) => BitConverter.ToSingle(code, o);
    static int Off(uint r) => (int)(r & 0xFFFFFF);

    /// <summary>
    /// Every surface the instance gets under these values: int (enum index),
    /// double[4] (colour), double (scalar) or string (material path), by name;
    /// unset parameters take their defaults.
    /// </summary>
    public List<Surface> Evaluate(IReadOnlyDictionary<string, object> values)
    {
        var run = new Run(this, values);
        var list = new List<Surface>();
        run.Instance(root, list, 0);
        return list;
    }

    sealed class Run
    {
        readonly MutableProgram p;
        readonly IReadOnlyDictionary<string, object> values;
        public Run(MutableProgram p, IReadOnlyDictionary<string, object> values) { this.p = p; this.values = values; }

        object Param(uint idx)
        {
            var par = p.parameters[(int)idx];
            if (values.TryGetValue(par.Name, out var v)) return v;
            var d = par.Default;
            if (d is JObject o) return new[] { (double?)o["X"] ?? 0, (double?)o["Y"] ?? 0, (double?)o["Z"] ?? 0, (double?)o["W"] ?? 1 };
            if (d == null || d.Type == JTokenType.Null) return null;
            return d.Type is JTokenType.Integer ? (object)(int)d : d.Type is JTokenType.Float ? (double)d : d.Type is JTokenType.Boolean ? ((bool)d ? 1 : 0) : (string)d;
        }

        T Switch<T>(int o, Func<uint, T> ev)
        {
            var x = Num(p.U(o + 1));
            var n = p.U(o + 9);
            for (var k = 0; k < n; k++)
                if (p.I(o + 13 + 8 * k) == x) return ev(p.U(o + 17 + 8 * k));
            var dflt = p.U(o + 5);
            return dflt != 0 ? ev(dflt) : default;
        }

        public int Num(uint r)
        {
            var o = Off(r);
            switch (p.code[o])
            {
                case 8: return Param(p.U(o + 1)) switch { int i => i, double d => (int)d, _ => 0 };
                case 3: return Num(p.U(o + 1)) == p.I(o + 5) ? 1 : 0;
                case 4: return Num(p.U(o + 1)) != 0 && Num(p.U(o + 5)) != 0 ? 1 : 0;
                case 5: return Num(p.U(o + 1)) != 0 || Num(p.U(o + 5)) != 0 ? 1 : 0;
                case 6: return Num(p.U(o + 1)) != 0 ? 0 : 1;
                default: throw new NotSupportedException($"Mutable int op {p.code[o]} at {o}");
            }
        }

        public double? Scalar(uint r)
        {
            if (r == 0) return null;
            var o = Off(r);
            switch (p.code[o])
            {
                case 11: return p.F(o + 1);
                case 12: return Param(p.U(o + 1)) switch { double d => d, int i => i, _ => null };
                case 13: return Scalar(Num(p.U(o + 1)) != 0 ? p.U(o + 5) : p.U(o + 9));
                case 14: return Switch(o, Scalar);
                default: throw new NotSupportedException($"Mutable scalar op {p.code[o]} at {o}");
            }
        }

        public double[] Colour(uint r)
        {
            if (r == 0) return null;
            var o = Off(r);
            switch (p.code[o])
            {
                case 19: return new double[] { p.F(o + 1), p.F(o + 5), p.F(o + 9), p.F(o + 13) };
                case 20: return Param(p.U(o + 1)) as double[];
                case 21: return Colour(Num(p.U(o + 1)) != 0 ? p.U(o + 5) : p.U(o + 9));
                case 22: return Switch(o, Colour);
                default: throw new NotSupportedException($"Mutable colour op {p.code[o]} at {o}");
            }
        }

        public Surface Material(uint r, string surface)
        {
            if (r == 0) return null;
            var o = Off(r);
            switch (p.code[o])
            {
                case 130:
                    return new Surface { Name = surface, Asset = p.passthrough.GetValueOrDefault(p.U(o + 5)) };
                case 131:
                {
                    var par = p.parameters[(int)p.U(o + 1)].Name;
                    return new Surface { Name = surface, MaterialParam = par, Asset = values.GetValueOrDefault(par) as string };
                }
                case 132: return Material(Num(p.U(o + 1)) != 0 ? p.U(o + 5) : p.U(o + 9), surface);
                case 133: return Switch(o, x => Material(x, surface));
                case 134:
                case 135:
                    return new Surface { Name = surface, Slot = p.names.GetValueOrDefault(p.U(o + 1)) };
                case 137:
                {
                    var s = Material(p.U(o + 1), surface);
                    if (s == null) return null;
                    var n = p.U(o + 5);
                    var q = o + 9;
                    for (var k = 0; k < n; k++)
                    {
                        var name = p.names.GetValueOrDefault(p.U(q));
                        var vr = p.U(q + 5);
                        q += 9;
                        var dt = vr >> 24;
                        if (dt == 0x14) { q += 4; continue; }     // an image (its layout index follows): the material's own
                        if (name == null) continue;
                        if (dt == 0x10 && Colour(vr) is { } c && !c.Any(double.IsNaN)) s.Vectors[name] = c;
                        else if (dt == 0x0c && Scalar(vr) is { } x && !double.IsNaN(x)) s.Scalars[name] = x;
                    }
                    return s;
                }
                default: throw new NotSupportedException($"Mutable material op {p.code[o]} at {o}");
            }
        }

        public void Instance(uint r, List<Surface> list, int depth)
        {
            if (r == 0 || depth > 200) return;
            var o = Off(r);
            switch (p.code[o])
            {
                case 116: Instance(Num(p.U(o + 1)) != 0 ? p.U(o + 5) : p.U(o + 9), list, depth + 1); return;
                case 117: Switch<object>(o, x => { Instance(x, list, depth + 1); return null; }); return;
                case 118: Instance(p.U(o + 1), list, depth + 1); Instance(p.U(o + 5), list, depth + 1); return;
                case 119: return;       // a component's mesh: the item names it
                case 121:
                case 122:
                {
                    Instance(p.U(o + 1), list, depth + 1);
                    var k = p.U(o + 9);
                    var name = p.code[o] == 121 ? p.names.GetValueOrDefault(k) : k < p.strings.Length ? p.strings[k] : null;
                    try
                    {
                        if (Material(p.U(o + 5), name) is { } s) list.Add(s);
                    }
                    catch (NotSupportedException) { /* a surface this reader can't follow keeps its material as is */ }
                    return;
                }
                default: throw new NotSupportedException($"Mutable instance op {p.code[o]} at {o}");
            }
        }
    }
}
