// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/MaterialService.cs - edit it there.
#nullable disable
using global::CUE4Parse.UE4.Assets.Exports.Texture;
using global::CUE4Parse_Conversion.Options;
using global::CUE4Parse_Conversion.Textures;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.MaterialPorter;

/// <summary>
/// Everything a Blender build needs about one material instance: its chain to
/// the master, the master's graph (dumped as ue_graph reads it) and asset
/// settings, and the parameter values the instance chain sets (child first).
/// </summary>
public sealed class MaterialInfo
{
    public string Name { get; set; }
    public string Path { get; set; }
    public string Master { get; set; }
    public string Graph { get; set; }
    public List<string> Chain { get; set; } = new();
    public Dictionary<string, object> Asset { get; set; } = new();
    public Dictionary<string, object> Overrides { get; set; } = new();
    public Dictionary<string, double> Scalars { get; set; } = new();
    public Dictionary<string, double[]> Vectors { get; set; } = new();
    public Dictionary<string, string> Textures { get; set; } = new();
    public Dictionary<string, bool> Switches { get; set; } = new();
    public Dictionary<string, bool[]> Masks { get; set; } = new();
    /// <summary>The Subsurface Profile skin scatters by (the nearest instance overriding it, else the master's).</summary>
    public SubsurfaceInfo Subsurface { get; set; }
    /// <summary>
    /// The master was cooked without its editor graph (a UEFN island's own
    /// material): nothing to translate, Blender builds an approximation from
    /// the textures and values.
    /// </summary>
    public bool Fallback { get; set; }
    /// <summary>Every texture the master samples, parameter or hard-coded (a fallback's only way to know the fixed ones).</summary>
    public List<string> ReferencedTextures { get; set; } = new();

    static readonly JsonSerializer Snake = JsonSerializer.Create(new JsonSerializerSettings
    {
        ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver
        {
            NamingStrategy = new Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy(),
        },
    });

    /// <summary>As the Blender extension reads it (snake_case; parameter names as they are).</summary>
    public JObject ToJson() => JObject.FromObject(this, Snake);
}

/// <summary>
/// A Subsurface Profile, as Blender's subsurface wants it: Radius (per
/// channel, relative) and Scale (metres). UE's Burley profile scatters over
/// MeanFreePathColor x MeanFreePathDistance / WorldUnitScale cm (Fortnite's
/// skin: ~2.6 / 1.5 / 0.7 mm, measured skin's range); the legacy one over
/// FalloffColor x ScatterRadius x WorldUnitScale cm.
/// </summary>
public sealed class SubsurfaceInfo
{
    public string Profile { get; set; }
    public double[] Radius { get; set; }
    public double Scale { get; set; }
}

/// <summary>A texture on disk, as Blender should read it.</summary>
public sealed class TextureFile
{
    public string File { get; set; }
    public bool Srgb { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
    /// <summary>"2d", "cube", "volume" or "array"; volumes and arrays are stacks of slices, slice 0 on top.</summary>
    public string Kind { get; set; } = "2d";
    public int Depth { get; set; } = 1;
    public bool Hdr { get; set; }
}

public sealed class MaterialService
{
    readonly GameContext game;
    readonly string cache;
    readonly SemaphoreSlim gate = new(1, 1);   // CUE4Parse loads, one at a time
    readonly Dictionary<string, object> memo = new();

    static readonly JsonSerializerSettings Ser = new() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

    public MaterialService(GameContext game)
    {
        this.game = game;
        cache = Directory.CreateDirectory(System.IO.Path.Combine(GameContext.DataDir, "cache")).FullName;
    }

    string Dir(string sub) => Directory.CreateDirectory(System.IO.Path.Combine(cache, game.BuildVersion, sub)).FullName;

    static string Safe(string key) =>
        string.Join("~", key.Replace(".o.uasset", "").Replace(".uasset", "").Split('/', StringSplitOptions.RemoveEmptyEntries));

    // ------------------------------------------------------------ paths
    /// <summary>
    /// "/Game/..", "/Engine/..", "/Plugin/..", "Pkg.Object", "Pkg.0" or a file
    /// key -> the file key of "&lt;package&gt;&lt;ext&gt;" if the game has it.
    /// </summary>
    public string ResolveKey(string p, string ext)
    {
        var provider = game.Provider;
        p = p.Trim();
        var dot = p.LastIndexOf('.');
        if (dot > p.LastIndexOf('/')) p = p[..dot];
        if (p.EndsWith(".o")) p = p[..^2];
        var tries = new List<string>();
        if (p.StartsWith("/Game/")) tries.Add("FortniteGame/Content/" + p[6..]);
        else if (p.StartsWith("/Engine/")) tries.Add("Engine/Content/" + p[8..]);
        else if (!p.StartsWith("/")) tries.Add(p);
        try { tries.Add(provider.FixPath(p)); } catch { /* not a mount path */ }
        foreach (var t in tries)
        {
            var baseKey = t;
            var d2 = baseKey.LastIndexOf('.');
            if (d2 > baseKey.LastIndexOf('/')) baseKey = baseKey[..d2];
            var k = baseKey + ext;
            if (provider.Files.TryGetValue(k, out var f)) return f.Path;
        }
        // a plugin mount: "/Plugin/Rest/Name" -> a key ending ".../Rest/Name<ext>" under that plugin
        if (p.StartsWith("/"))
        {
            var parts = p.Trim('/').Split('/');
            var tail = "/" + string.Join('/', parts.Skip(1)) + ext;
            var hit = provider.Files.Keys.FirstOrDefault(k => k.EndsWith(tail, StringComparison.OrdinalIgnoreCase)
                                                             && k.Contains("/" + parts[0] + "/", StringComparison.OrdinalIgnoreCase));
            if (hit != null) return provider.Files[hit].Path;
        }
        return null;
    }

    /// <summary>"/Game/X/T_A.0" (CUE4Parse's export index) -> "/Game/X/T_A.T_A".</summary>
    public static string ObjectPath(JToken reference)
    {
        if (reference == null || reference.Type != JTokenType.Object) return null;
        var path = (string)reference["ObjectPath"];
        var name = (string)reference["ObjectName"] ?? "";
        if (string.IsNullOrEmpty(path)) return null;
        var q = name.IndexOf('\'');
        if (q >= 0) name = name[(q + 1)..].TrimEnd('\'');
        name = name.Split(':').Last().Split('.').Last();
        var dot = path.LastIndexOf('.');
        return dot > 0 && path[(dot + 1)..].All(char.IsDigit) ? path[..dot] + "." + name : path;
    }

    async Task<T> Locked<T>(Func<Task<T>> f)
    {
        await gate.WaitAsync();
        try { return await f(); }
        finally { gate.Release(); }
    }

    /// <summary>A package's main export (the one named after it), as JSON.</summary>
    async Task<JObject> MainExportAsync(string path)
    {
        var key = ResolveKey(path, ".uasset") ?? throw new FileNotFoundException("No package for " + path);
        var pkg = await game.Provider.LoadPackageAsync(key);
        var name = System.IO.Path.GetFileNameWithoutExtension(key);
        var obj = pkg.GetExports().FirstOrDefault(e => e.Name == name) ?? pkg.GetExports().First();
        return JObject.Parse(JsonConvert.SerializeObject(obj, Ser));
    }

    // ------------------------------------------------------------ graphs
    /// <summary>
    /// The expression graph of a material or material function (it lives in the
    /// editor-only package, &lt;path&gt;.o.uasset), dumped as ue_graph reads it.
    /// </summary>
    public Task<string> GraphAsync(string path) => Locked(async () =>
    {
        var key = ResolveKey(path, ".o.uasset") ?? throw new FileNotFoundException("No editor graph for " + path);
        var file = System.IO.Path.Combine(Dir("graphs"), Safe(key) + ".json");
        if (File.Exists(file)) return file;
        var pkg = await game.Provider.LoadPackageAsync(key);
        await File.WriteAllTextAsync(file, JsonConvert.SerializeObject(pkg.GetExports().ToArray(), Formatting.None, Ser));
        return file;
    });

    // ------------------------------------------------------------ instances
    /// <summary>An instance (or a material) and everything its chain sets, child first.</summary>
    public async Task<MaterialInfo> DescribeAsync(string path)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var info = await Locked(() => ChainAsync(path));
        if (info.Master != null && ResolveKey(info.Master, ".o.uasset") == null)
        {
            info.Fallback = true;
            await Locked(() => CookedDefaultsAsync(info));
        }
        else if (info.Master != null) info.Graph = await GraphAsync(info.Master);
        Timing.Log("describe " + Bridge.ShortName(path), sw);
        return info;
    }

    async Task<MaterialInfo> ChainAsync(string path)
    {
        var info = new MaterialInfo { Path = path, Name = path.Split('/').Last().Split('.').Last() };
        var cur = path;
        string profile = null;
        for (var depth = 0; depth < 24 && cur != null; depth++)
        {
            var obj = await MainExportAsync(cur);
            info.Chain.Add(cur);
            var p = obj["Properties"] as JObject ?? new JObject();
            // an instance's profile counts when it overrides; the master's otherwise
            if (profile == null && ((string)obj["Type"] == "Material" || (bool?)p["bOverrideSubsurfaceProfile"] == true))
                profile = ObjectPath(p["SubsurfaceProfile"]);
            if ((string)obj["Type"] == "Material")
            {
                info.Master = cur;
                foreach (var k in new[] { "BlendMode", "ShadingModel", "TwoSided", "OpacityMaskClipValue", "bUseMaterialAttributes",
                                          "bTangentSpaceNormal", "MaterialDomain", "bIsSky", "bUsedWithSkeletalMesh" })
                    if (p[k] != null) info.Asset[k] = p[k].ToObject<object>();
                // a master's own parameters are its graph's defaults: the translator reads those
                break;
            }
            Collect(p, info);
            cur = ObjectPath(p["Parent"]);
        }
        if (profile != null)
        {
            try { info.Subsurface = await ProfileAsync(profile); }
            catch { /* no profile to read: Blender's skin radius */ }
        }
        return info;
    }

    /// <summary>
    /// A cooked master's parameter defaults (CachedExpressionData: each runtime
    /// parameter type's names beside its values) where the instances set none,
    /// and every texture it references.
    /// </summary>
    async Task<bool> CookedDefaultsAsync(MaterialInfo info)
    {
        var obj = await MainExportAsync(info.Master);
        if (obj["CachedExpressionData"] is JObject ced)
        {
            JArray Names(int type) => ced[type == 0 ? "RuntimeEntries" : $"RuntimeEntries[{type}]"]?["ParameterInfoSet"] as JArray ?? new JArray();
            var scalars = ced["ScalarValues"] as JArray ?? new JArray();
            var vectors = ced["VectorValues"] as JArray ?? new JArray();
            var textures = ced["TextureValues"] as JArray ?? new JArray();
            var n = Names(0);
            for (var i = 0; i < n.Count && i < scalars.Count; i++)
                if ((string)n[i]["Name"] is { } name) info.Scalars.TryAdd(name, (double?)scalars[i] ?? 0);
            n = Names(1);
            for (var i = 0; i < n.Count && i < vectors.Count; i++)
                if ((string)n[i]["Name"] is { } name && vectors[i] is JObject v)
                    info.Vectors.TryAdd(name, new[] { (double?)v["R"] ?? 0, (double?)v["G"] ?? 0, (double?)v["B"] ?? 0, (double?)v["A"] ?? 1 });
            n = Names(3);
            for (var i = 0; i < n.Count && i < textures.Count; i++)
                if ((string)n[i]["Name"] is { } name && ObjectPath(textures[i]) is { } t) info.Textures.TryAdd(name, t);
        }
        try
        {
            if (await game.Provider.LoadPackageObjectAsync(info.Master) is global::CUE4Parse.UE4.Assets.Exports.Material.UMaterial m)
            {
                var list = new List<global::CUE4Parse.UE4.Assets.Exports.Material.UUnrealMaterial>();
                m.AppendReferencedTextures(list, false);
                foreach (var t in list.OfType<UTexture>())
                    if (t.GetPathName() is { } tp && !info.ReferencedTextures.Contains(tp)) info.ReferencedTextures.Add(tp);
            }
        }
        catch { /* only the parameters' textures, then */ }
        foreach (var t in info.Textures.Values)
            if (!info.ReferencedTextures.Contains(t)) info.ReferencedTextures.Add(t);
        return true;
    }

    async Task<SubsurfaceInfo> ProfileAsync(string path)
    {
        var s = (await MainExportAsync(path))["Properties"]?["Settings"];
        if (s == null) return null;
        double F(string k, double d) => (double?)s[k] ?? d;
        double[] Rgb(string k) => s[k] is JObject c ? new[] { (double?)c["R"] ?? 1, (double?)c["G"] ?? 1, (double?)c["B"] ?? 1 } : new[] { 1.0, 0.2, 0.1 };
        var wus = Math.Max(1e-4, F("WorldUnitScale", 0.1));
        var burley = (bool?)s["bEnableBurley"] ?? true;
        var cm = burley ? F("MeanFreePathDistance", 1.2) / wus : F("ScatterRadius", 1.2) * wus;
        return new SubsurfaceInfo
        {
            Profile = path.Split('/').Last().Split('.').Last(),
            Radius = burley ? Rgb("MeanFreePathColor") : Rgb("FalloffColor"),
            Scale = cm * 0.01,
        };
    }

    /// <summary>One level of the chain: values the child didn't set already.</summary>
    static void Collect(JObject p, MaterialInfo info)
    {
        static string Name(JToken e) => (string)e["ParameterInfo"]?["Name"] ?? (string)e["ParameterName"];
        foreach (var e in p["ScalarParameterValues"] ?? new JArray())
            info.Scalars.TryAdd(Name(e), (double)e["ParameterValue"]);
        foreach (var e in p["VectorParameterValues"] ?? new JArray())
        {
            var v = e["ParameterValue"];
            info.Vectors.TryAdd(Name(e), new[] { (double)v["R"], (double)v["G"], (double)v["B"], (double?)v["A"] ?? 1.0 });
        }
        foreach (var e in p["TextureParameterValues"] ?? new JArray())
        {
            var t = ObjectPath(e["ParameterValue"]);
            if (t != null) info.Textures.TryAdd(Name(e), t);
        }
        // static values: UE 5 keeps them in StaticParametersRuntime (older builds, StaticParameters)
        foreach (var sp in new[] { p["StaticParametersRuntime"], p["StaticParameters"] })
        {
            if (sp == null) continue;
            foreach (var e in sp["StaticSwitchParameters"] ?? new JArray())
                info.Switches.TryAdd(Name(e), (bool?)e["Value"] ?? false);
            foreach (var e in sp["StaticComponentMaskParameters"] ?? new JArray())
                info.Masks.TryAdd(Name(e), new[] { (bool?)e["R"] ?? false, (bool?)e["G"] ?? false, (bool?)e["B"] ?? false, (bool?)e["A"] ?? false });
        }
        // an override set to the struct's default value (Opaque, DefaultLit, one-sided...)
        // isn't serialized, only its bOverride_ flag: that default is the override
        if (p["BasePropertyOverrides"] is JObject o)
            foreach (var (k, d) in OverrideDefaults)
                if ((bool?)o["bOverride_" + k] == true)
                    info.Overrides.TryAdd(k, o[k]?.ToObject<object>() ?? d);
    }

    /// <summary>FMaterialInstanceBasePropertyOverrides' defaults (its constructor).</summary>
    static readonly (string Key, object Default)[] OverrideDefaults =
    {
        ("BlendMode", "EBlendMode::BLEND_Opaque"), ("ShadingModel", "EMaterialShadingModel::MSM_DefaultLit"),
        ("TwoSided", false), ("OpacityMaskClipValue", 0.333333), ("bIsThinSurface", false),
    };

    // ------------------------------------------------------------ textures
    readonly System.Collections.Concurrent.ConcurrentDictionary<string, Lazy<Task<TextureFile>>> textures = new(StringComparer.OrdinalIgnoreCase);
    readonly SemaphoreSlim encoders = new(Math.Max(2, Environment.ProcessorCount / 2));

    /// <summary>
    /// A texture decoded to a file in the cache (PNG, or HDR for float
    /// formats), with a sidecar record so a later session reuses it. One task
    /// per texture: a prefetch and Blender's request share it.
    /// </summary>
    /// <summary>
    /// The largest mip textures are exported at (0: full size). A map import
    /// sets it for its duration: hundreds of full-size textures are what makes a
    /// map scene slow to show in Blender, and the smaller mips are often in the
    /// install already (no CDN download).
    /// </summary>
    public int MaxTextureSize { get; set; }

    /// <summary>A texture as a PNG (HDR for float formats): what the app shows and the Files page exports.</summary>
    public Task<TextureFile> TextureAsync(string path) => TextureAsync(path, false);

    /// <summary>
    /// A texture for Blender: where Blender reads the game's own compression
    /// (BC1/BC3/BC5/BC7, BGRA8) the mip's data as it is in a DDS - no decode,
    /// no encode, and Blender loads it faster than a PNG; else the PNG.
    /// </summary>
    public Task<TextureFile> BlenderTextureAsync(string path) => TextureAsync(path, true);

    Task<TextureFile> TextureAsync(string path, bool raw)
    {
        var cap = MaxTextureSize;
        var key = (cap > 0 ? path + "@" + cap : path) + (raw ? "#dds" : "");
        var lazy = textures.GetOrAdd(key, _ => new Lazy<Task<TextureFile>>(() =>
        {
            var t = Task.Run(() => ExportTextureAsync(path, cap, raw));
            // a failure isn't kept: the next ask tries again
            t.ContinueWith(_ => textures.TryRemove(key, out var _), TaskContinuationOptions.OnlyOnFaulted);
            return t;
        }));
        return lazy.Value;
    }

    /// <summary>The game's pixel formats Blender reads from a DDS as they are (DXGI format numbers).</summary>
    static readonly Dictionary<string, uint> RawFormats = new()
    {
        ["PF_DXT1"] = 71, ["PF_DXT3"] = 74, ["PF_DXT5"] = 77, ["PF_BC5"] = 83, ["PF_BC7"] = 98, ["PF_B8G8R8A8"] = 87,
    };

    /// <summary>One mip's data as a DDS file (DX10 header, a single 2D surface).</summary>
    static void WriteDds(string file, int width, int height, uint dxgi, byte[] data)
    {
        using var f = new BinaryWriter(File.Create(file));
        f.Write(0x20534444u);                                   // "DDS "
        f.Write(124u);
        f.Write(0x1u | 0x2u | 0x4u | 0x1000u | 0x80000u);       // caps, height, width, pixel format, linear size
        f.Write((uint)height);
        f.Write((uint)width);
        f.Write((uint)data.Length);
        f.Write(0u);                                            // depth
        f.Write(1u);                                            // mips
        for (var i = 0; i < 11; i++) f.Write(0u);
        f.Write(32u); f.Write(0x4u); f.Write(0x30315844u);      // pixel format: FourCC "DX10"
        for (var i = 0; i < 5; i++) f.Write(0u);
        f.Write(0x1000u); f.Write(0u); f.Write(0u); f.Write(0u); f.Write(0u);
        f.Write(dxgi); f.Write(3u); f.Write(0u); f.Write(1u); f.Write(0u);   // 2D texture, one
        f.Write(data);
    }

    /// <summary>Textures Blender will soon ask for, exported in the background meanwhile.</summary>
    public void Prefetch(IEnumerable<string> paths)
    {
        foreach (var p in paths.Where(p => !string.IsNullOrEmpty(p)))
            _ = BlenderTextureAsync(p).ContinueWith(t => _ = t.Exception, TaskContinuationOptions.OnlyOnFaulted);
    }

    /// <summary>Bumped when what a cached texture file holds changes.</summary>
    const int TextureCacheVersion = 2;

    async Task<TextureFile> ExportTextureAsync(string path, int cap = 0, bool raw = false)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var tex = await game.Provider.LoadPackageObjectAsync<UTexture>(path);
        var stem = System.IO.Path.Combine(Dir("textures"), Safe(ResolveKey(path, ".uasset") ?? path));
        // a copy made while the full-size mips couldn't stream is made again once they can
        var full = tex.PlatformData?.Mips?.FirstOrDefault()?.SizeX ?? 0;
        if (cap > 0 && full > cap)
        {
            stem += "@" + cap;      // kept apart from the full-size copy
            full = cap;
        }
        else cap = 0;
        var meta = stem + (raw ? ".dds" : "") + ".meta.json";
        try
        {
            if (File.Exists(meta))
            {
                var rec = JsonConvert.DeserializeObject<CachedTexture>(await File.ReadAllTextAsync(meta));
                if (rec?.Version == TextureCacheVersion && rec.Texture != null && File.Exists(rec.Texture.File) && rec.Texture.Width >= full)
                {
                    Timing.Log($"texture {Bridge.ShortName(path)} (cached)", sw);
                    return rec.Texture;
                }
            }
        }
        catch { /* a broken record: export again */ }

        // the mip's own data, when Blender reads its format: nothing to decode or encode
        if (raw && tex is UTexture2D t2 && t2.PlatformData is { } pd && pd.VTData == null && RawFormats.TryGetValue(pd.PixelFormat ?? "", out var dxgi))
        {
            try
            {
                var mip = pd.Mips.Where(m => cap <= 0 || m.SizeX <= cap).FirstOrDefault(m => m.EnsureValidBulkData(null, 0));
                if (mip?.BulkData?.Data is { Length: > 0 } bytes)
                {
                    var file = stem + ".dds";
                    WriteDds(file, mip.SizeX, mip.SizeY, dxgi, bytes);
                    var rec = new TextureFile { File = file, Srgb = tex.SRGB, Width = mip.SizeX, Height = mip.SizeY };
                    await File.WriteAllTextAsync(meta, JsonConvert.SerializeObject(new CachedTexture { Version = TextureCacheVersion, Texture = rec }));
                    Timing.Log($"texture {Bridge.ShortName(path)} {mip.SizeX}x{mip.SizeY} {pd.PixelFormat} as DDS", sw);
                    return rec;
                }
            }
            catch (Exception e) { Timing.Log($"texture {Bridge.ShortName(path)}: raw copy failed ({e.Message}), decoded", sw); }
        }

        await encoders.WaitAsync();
        try
        {
            var tLoad = sw.Elapsed.TotalMilliseconds;
            var ct = (cap > 0 ? TextureDecoder.Decode(tex, cap, ETexturePlatform.DesktopMobile) : tex.Decode(ETexturePlatform.DesktopMobile))
                     ?? throw new InvalidDataException("Could not decode " + path);
            var tDecode = sw.Elapsed.TotalMilliseconds;
            var (data, ext) = EncodeTexture(ct);
            var tEncode = sw.Elapsed.TotalMilliseconds;
            var file = stem + "." + ext;
            await File.WriteAllBytesAsync(file, data);
            var kind = tex switch
            {
                UTextureCube => "cube",
                UVolumeTexture => "volume",
                UTexture2DArray => "array",
                _ => "2d",
            };
            var depth = kind is "volume" or "array" && ct.Width > 0 ? Math.Max(1, ct.Height / ct.Width) : 1;
            var result = new TextureFile
            {
                File = file, Srgb = tex.SRGB, Width = ct.Width, Height = ct.Height, Kind = kind, Depth = depth,
                Hdr = ext == "hdr",
            };
            await File.WriteAllTextAsync(meta, JsonConvert.SerializeObject(new CachedTexture { Version = TextureCacheVersion, Texture = result }));
            Timing.Log($"texture {Bridge.ShortName(path)} {ct.Width}x{ct.Height} {ct.PixelFormat}: load {tLoad:0} decode {tDecode - tLoad:0} encode {tEncode - tDecode:0} ({data.Length / 1024} KB)", sw);
            return result;
        }
        finally { encoders.Release(); }
    }

    sealed class CachedTexture
    {
        public int Version { get; set; }
        public TextureFile Texture { get; set; }
    }

    /// <summary>
    /// 8-bit colour straight to PNG with Skia at a fast setting (Sub filter,
    /// zlib 1): 3-6x quicker than the library's default (all filters, zlib 6)
    /// for files about a third bigger. Anything else goes through global::CUE4Parse.
    /// </summary>
    static (byte[] Data, string Ext) EncodeTexture(CTexture ct)
    {
        var type = ct.PixelFormat switch
        {
            EPixelFormat.PF_R8G8B8A8 => SkiaSharp.SKColorType.Rgba8888,
            EPixelFormat.PF_B8G8R8A8 => SkiaSharp.SKColorType.Bgra8888,
            _ => SkiaSharp.SKColorType.Unknown,
        };
        if (type != SkiaSharp.SKColorType.Unknown && ct.Data != null && ct.Data.Length >= ct.Width * ct.Height * 4)
        {
            var info = new SkiaSharp.SKImageInfo(ct.Width, ct.Height, type, SkiaSharp.SKAlphaType.Unpremul);
            var pin = System.Runtime.InteropServices.GCHandle.Alloc(ct.Data, System.Runtime.InteropServices.GCHandleType.Pinned);
            try
            {
                using var pm = new SkiaSharp.SKPixmap(info, pin.AddrOfPinnedObject());
                using var png = pm.Encode(new SkiaSharp.SKPngEncoderOptions(SkiaSharp.SKPngEncoderFilterFlags.Sub, 1));
                if (png != null) return (png.ToArray(), "png");
            }
            finally { pin.Free(); }
        }
        var opts = new ExportOptions(texturePlatform: ETexturePlatform.DesktopMobile, textureFormat: ETextureFormat.Png,
                                     exportHdrTexturesAsHdr: true);
        var data = ct.Encode(opts, out var ext);
        return (data, ext.Trim('.').ToLowerInvariant());
    }

    // ------------------------------------------------------------ collections
    /// <summary>A material parameter collection's defaults: {"scalars": {..}, "vectors": {..}}.</summary>
    public Task<JObject> CollectionAsync(string path) => Locked(async () =>
    {
        var p = (await MainExportAsync(path))["Properties"] as JObject ?? new JObject();
        var scalars = new JObject();
        var vectors = new JObject();
        foreach (var e in p["ScalarParameters"] ?? new JArray())
            scalars[(string)e["ParameterName"]] = (double?)e["DefaultValue"] ?? 0.0;
        foreach (var e in p["VectorParameters"] ?? new JArray())
        {
            // left out when it's the struct's own default, (0,0,0,0) (FCollectionVectorParameter: ForceInitToZero)
            var v = e["DefaultValue"];
            vectors[(string)e["ParameterName"]] = new JArray((double?)v?["R"] ?? 0, (double?)v?["G"] ?? 0, (double?)v?["B"] ?? 0, (double?)v?["A"] ?? 0);
        }
        return new JObject { ["scalars"] = scalars, ["vectors"] = vectors };
    });

    /// <summary>A package's main export as JSON (the details view shows it raw).</summary>
    public Task<JObject> RawAsync(string path) => Locked(() => MainExportAsync(path));
}
