# Generated by materialporter/tools/sync_fork.py from blender/material_porter/env.py - edit it there.
"""What a UE material reads from the world, for a material on a mesh in Blender.

The translator (ue_graph) asks its env for everything outside the graph. This
one answers for a FortnitePorting import:

* UE space: FP mirrors Y and scales by 0.01, so a Blender world vector is
  (x, -y, z) in UE, and a position that times 100 (cm).
* A material's graph is one node group (its "root"); each parameter is an
  input of it - a float, a colour (and its alpha) - holding the instance's
  value on the material's group node, as a UE material instance shows them.
  Inputs sit in panels named after the function they're read through
  ("Material" for the master's own), alphabetical within; unused ones go.
  Inside a function group a parameter is a socket of that group ("P: Name"),
  so groups stay shareable between instances.
* Static switches, component masks and texture parameters come from the
  instance chain (the app merged it, child first).
* Graphs and textures come from the app, as the build reaches them.
* Mesh inputs use FP's names: UV maps "UV0", "UV1"..., vertex colour "COL0".
"""
import bpy

from .ue_graph import WATER_DEPTH_DEFAULT, Val

COLORSPACE_SRGB = "sRGB"
COLORSPACE_DATA = "Non-Color"
# a water surface's depth, baked by a map import (water.bake_water): x the
# metres down to the ground under each vertex, y 1 where it was baked
WATER_ATTRIBUTE = "mp_water"

# images this session loaded, by file: a map's hundreds of materials share
# textures, and images.load(check_existing=True) walks every image each time
_LOADED = {}


def _load(path, w, h):
    """An image for this file: the one loaded before (still there), else loaded
    (an older, smaller copy the file already had is reloaded; reading its size
    decodes it, so a fresh load isn't asked)."""
    img = _LOADED.get(path)
    if img is not None:
        try:
            img.name
            return img
        except ReferenceError:      # removed since
            pass
    known = len(bpy.data.images)
    img = bpy.data.images.load(path, check_existing=True)
    if len(bpy.data.images) == known and w and h and tuple(img.size) != (w, h):
        img.reload()
    _LOADED[path] = img
    return img


class MaterialEnv:
    nest_functions = True
    asset_paths = True          # textures and collections by object path
    replace_groups = False      # other materials' groups stay
    function_prefix = ""

    def __init__(self, app, entry, objects=()):
        self.app, self.entry = app, entry
        self.objects = [o for o in objects if o is not None]
        self.h = [None]
        self._once = {}
        self._images = {}
        self._defaults = {}
        self.notes = []
        self.root = None        # the material's node group: parameters become its inputs
        self.caller = None      # the function a parameter is reached through (its panel)
        self._params = {}       # key -> (interface item, Val, value, panel name)
        self._claimed = {}      # (image, channel) -> the channel mask guessed onto it
        self._panels = {}
        # what another instance of the same shape needs to reuse this build (build.build_like):
        # which parameters each texture came from, each parameter's graph default, normal maps;
        # False when the trees hold more than parameter values (a guessed mask, the object's
        # bounds, a texture array's slices, a baked value)
        self.reusable = True
        self.tex_params = {}        # texture key -> {parameter names that resolved to it}
        self.tex_default = {}       # texture parameter -> its graph default key
        self.tex_normal = set()     # keys sampled as normal maps
        self.graph_defaults = {}    # "P: name" / "V: name" -> the graph's default

    # ------------------------------------------------------------ plumbing
    @property
    def tr(self):
        return self.h[0]

    def current(self):
        return self.h[0]

    def set_current(self, tr):
        self.h[0] = tr

    def once(self, key, make):
        k = (self.tr.tree.as_pointer(), key)
        if k not in self._once:
            self._once[k] = make()
        return self._once[k]

    def note(self, text):
        if text not in self.notes:
            self.notes.append(text)

    def _ue(self, v, scale=1.0):
        """A Blender vector in UE space (Y mirrored), times `scale`."""
        return self.tr.vmath('MULTIPLY', v, self.tr.const((scale, -scale, scale), 3), out_w=3)

    def _geo(self):
        return self.once("geo", lambda: self.tr.node("ShaderNodeNewGeometry", "geometry"))

    # ------------------------------------------------------------ view and world
    def camera_vector(self):
        return self.once("camvec", lambda: self._ue(Val(self._geo().outputs["Incoming"], 3)))

    def world_position(self, camera_relative=False):
        p = self.once("wpos", lambda: self._ue(Val(self._geo().outputs["Position"], 3), 100.0))
        return self.tr.vmath('SUBTRACT', p, self.camera_position(), out_w=3) if camera_relative else p

    def camera_position(self):
        def make():
            # the camera is where the view ray leaves: P + Incoming * view distance
            cam = self.tr.node("ShaderNodeCameraData", "camera data")
            geo = self._geo()
            ray = self.tr.vmath('SCALE', Val(geo.outputs["Incoming"], 3), Val(cam.outputs["View Distance"], 1), out_w=3)
            return self._ue(self.tr.vmath('ADD', Val(geo.outputs["Position"], 3), ray, out_w=3), 100.0)
        return self.once("campos", make)

    def actor_position(self, camera_relative=False):
        def make():
            n = self.tr.node("ShaderNodeObjectInfo", "object info")
            return self._ue(Val(n.outputs["Location"], 3), 100.0)
        p = self.once("actor", make)
        return self.tr.vmath('SUBTRACT', p, self.camera_position(), out_w=3) if camera_relative else p

    def light_direction(self):
        """Towards the scene's sun (its lamp shines down its local -Z)."""
        sun = next((o for o in bpy.context.scene.objects if o.type == 'LIGHT' and o.data.type == 'SUN'), None)
        if sun is None:
            self.note("no sun lamp: light straight overhead")
            return self.tr.const((0.0, 0.0, 1.0), 3)
        z = sun.matrix_world.to_3x3().col[2].normalized()
        return self.tr.const((z.x, -z.y, z.z), 3)

    def view_luminance(self, direction):
        self.note("sky atmosphere read as a flat sky colour")
        return self.tr.const((0.4, 0.5, 0.7), 3)

    def time(self):
        def make():
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeValue", "Time (s)")
            d = n.outputs[0].driver_add("default_value").driver
            d.type = 'SCRIPTED'
            d.expression = "frame / %g" % (bpy.context.scene.render.fps / bpy.context.scene.render.fps_base)
            return Val(n.outputs[0], 1)
        return self.once("time", make)

    def cloud_sample(self, out):
        return self.tr.const(0.0)

    # ------------------------------------------------------------ mesh
    def uv(self, index):
        def make():
            n = self.tr.node("ShaderNodeUVMap", "UV%d" % index)
            n.uv_map = "UV%d" % index
            u, v = self.tr.comps(Val(n.outputs[0], 3))[:2]
            # UE's V runs down
            return self.tr.combine([u, self.tr.binop('SUBTRACT', self.tr.const(1.0), v)])
        return self.once("uv%d" % index, make)

    def landscape_weight(self, name):
        """A landscape layer's weight: the exported landscape's colour layer of
        that name (a grey weight: its red channel); on another mesh, or where
        a component doesn't paint the layer, 0."""
        def make():
            n = self.tr.node("ShaderNodeVertexColor", "layer " + name)
            n.layer_name = name
            return self.tr.comps(Val(n.outputs["Color"], 3))[0]
        return self.once("layer " + name, make)

    def landscape_uv(self, index):
        """A landscape's texture coordinates (UV0: landscape-wide quads, as the
        export writes them)."""
        return self.uv(index)

    def vertex_color(self):
        def make():
            n = self.tr.node("ShaderNodeVertexColor", "COL0")
            n.layer_name = "COL0"
            return Val(n.outputs["Color"], 3), Val(n.outputs["Alpha"], 1)
        return self.once("col0", make)

    def water_depth(self):
        """How deep the water is under a water surface's pixel, UE cm - at
        run time the water info texture's water height less its ground
        height: the depth a map import bakes onto the surface mesh (the
        mp_water attribute), elsewhere the translator's default."""
        tr = self.tr

        def make():
            n = tr.node("ShaderNodeAttribute", "water depth (baked)")
            n.attribute_type = 'GEOMETRY'
            n.attribute_name = WATER_ATTRIBUTE
            metres, known = tr.comps(Val(n.outputs["Vector"], 3))[:2]
            return tr.lerp(tr.const(WATER_DEPTH_DEFAULT), tr.binop('MULTIPLY', metres, tr.const(100.0)), known,
                           label="water depth (cm)")
        return self.once("water depth", make)

    def local_bounds(self):
        """The first target object's bounding box, in UE cm (materials are
        shared, so it's one object's: the one the material was built for)."""
        self.reusable = False
        obj = next((o for o in self.objects if o.type == 'MESH'), None)
        if obj is None:
            return None
        xs = [c[0] for c in obj.bound_box]
        ys = [-c[1] for c in obj.bound_box]
        zs = [c[2] for c in obj.bound_box]
        return (self.tr.const((min(xs) * 100, min(ys) * 100, min(zs) * 100), 3),
                self.tr.const((max(xs) * 100, max(ys) * 100, max(zs) * 100), 3))

    # ------------------------------------------------------------ parameters
    def _at_root(self):
        return self.root is not None and self.tr.tree == self.root and self.tr.function is None

    def _root_input(self, key, label, socket_type, value, width, description):
        """A parameter as an input of the material's group (made once)."""
        if key in self._params:
            return self._params[key][1]
        item = self.root.interface.new_socket(label, description=description, in_out='INPUT', socket_type=socket_type)
        item.default_value = value
        if socket_type == 'NodeSocketFloat':
            item.min_value, item.max_value = -1e9, 1e9
        gi = self.once("parameters", lambda: self.tr.node("NodeGroupInput", "parameters"))
        v = Val(next(s for s in gi.outputs if s.identifier == item.identifier), width)
        self._params[key] = (item, v, value, self.caller or "Material")
        return v

    def finish_parameters(self):
        """Unused inputs go; the rest in panels by function ("Material" first),
        alphabetical within - or one alphabetical list when there's one
        function. Returns [(identifier, value)] for the group node's sockets."""
        if self.root is None:
            return []
        iface = self.root.interface
        gi = next((n for n in self.root.nodes if n.bl_idname == "NodeGroupInput"), None)
        linked = {s.identifier for s in gi.outputs if s.is_linked} if gi else set()
        for key, (item, _v, _value, _panel) in list(self._params.items()):
            if item.identifier not in linked:
                iface.remove(item)
                del self._params[key]
        by_panel = {}
        for item, _v, _value, panel in self._params.values():
            by_panel.setdefault(panel, []).append(item)
        order = sorted(by_panel, key=lambda n: (n != "Material", n.lower()))
        if len(order) == 1:
            for i, item in enumerate(sorted(by_panel[order[0]], key=lambda it: it.name.lower())):
                iface.move(item, i)
        else:
            for name in order:
                panel = iface.new_panel(name, default_closed=True)
                self._panels[name] = panel
                for i, item in enumerate(sorted(by_panel[name], key=lambda it: it.name.lower())):
                    iface.move_to_parent(item, panel, i)
        return [(item.identifier, value) for item, _v, value, _panel in self._params.values()]

    def node_width(self):
        """Wide enough for the longest input's name and its value."""
        names = [item.name for item, _v, _value, _panel in self._params.values()] + list(self._panels)
        longest = max((len(n) for n in names), default=10)
        return max(240, min(700, int(7.4 * longest + 110)))

    def scalar(self, name, default):
        if not name:
            # an unnamed parameter ("None" in UE): nothing can set it, its default stands
            return self.tr.const(float(default or 0.0))
        v = float(self.entry.get("scalars", {}).get(name, default))
        self.graph_defaults.setdefault("P: " + name, float(default or 0.0))
        self._defaults["P: " + name] = v
        fn = self.tr.function
        if fn is not None:
            return fn.env_input("P: " + name, 'NodeSocketFloat', v, "UE scalar parameter " + name)
        if self._at_root():
            return self._root_input("P: " + name, name, 'NodeSocketFloat', v, 1, "UE scalar parameter")

        def make():
            self.reusable = False       # the value is baked into the tree
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeValue", name)
            n.outputs[0].default_value = v
            return Val(n.outputs[0], 1)
        return self.once("P: " + name, make)

    def vector(self, name, rgba):
        if not name:
            rgba = tuple(rgba) + (1.0,) * (4 - len(rgba))
            return self.tr.const(tuple(float(x) for x in rgba[:3]), 3), self.tr.const(float(rgba[3]))
        self.graph_defaults.setdefault("V: " + name, tuple(float(x) for x in rgba) + (1.0,) * (4 - len(rgba)))
        rgba = tuple(self.entry.get("vectors", {}).get(name, rgba)) + (1.0,) * (4 - len(rgba))
        self._defaults["V: " + name] = rgba
        alpha = self.tr.const(float(rgba[3]))
        fn = self.tr.function
        if fn is not None:
            return fn.env_input("V: " + name, 'NodeSocketColor', rgba, "UE vector parameter " + name), alpha
        if self._at_root():
            return (self._root_input("V: " + name, name, 'NodeSocketColor', rgba, 3, "UE vector parameter"),
                    self._root_input("A: " + name, name + " (A)", 'NodeSocketFloat', float(rgba[3]), 1,
                                     "UE vector parameter, its alpha"))

        def make():
            self.reusable = False       # the value is baked into the tree
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeRGB", name)
            n.outputs[0].default_value = rgba
            return Val(n.outputs[0], 3)
        return self.once("V: " + name, make), alpha

    def primitive_data(self, v, index, w):
        """UE's Custom Primitive Data: floats a placed component carries (a
        tree's season tint), read from the object's custom properties
        mp_cpd<index> (a map import sets them, with mp_cpd = 1); an object
        without them keeps the material's own value `v`."""
        tr = self.tr

        def attr(name):
            def make():
                with tr.at("Parameters"):
                    n = tr.node("ShaderNodeAttribute", name)
                n.attribute_type = 'OBJECT'
                n.attribute_name = name
                return Val(n.outputs["Fac"], 1)
            return self.once("attr " + name, make)
        flag = attr("mp_cpd")
        if w == 1:
            data = attr("mp_cpd%d" % index)
            return tr.math('ADD', v, tr.math('MULTIPLY', tr.math('SUBTRACT', data, v), flag))
        data = tr.combine([attr("mp_cpd%d" % (index + i)) for i in range(3)])
        return tr.vmath('ADD', v, tr.vmath('SCALE', tr.vmath('SUBTRACT', data, v, out_w=3), flag, out_w=3), out_w=3)

    def instance_data(self, v, index, w):
        """UE's PerInstanceCustomData: an instanced mesh's own floats, from
        the object's mp_pic<index> properties; the material's default `v`
        where the instance has fewer than index + w of them (mp_pic: how
        many, 0 on other objects), as UE reads past NumCustomDataFloats."""
        tr = self.tr

        def attr(name):
            def make():
                with tr.at("Parameters"):
                    n = tr.node("ShaderNodeAttribute", name)
                n.attribute_type = 'OBJECT'
                n.attribute_name = name
                return Val(n.outputs["Fac"], 1)
            return self.once("attr " + name, make)
        has = tr.math('GREATER_THAN', attr("mp_pic"), tr.const(float(index + w - 1) + 0.5))
        if w == 1:
            data = attr("mp_pic%d" % index)
            return tr.math('ADD', v, tr.math('MULTIPLY', tr.math('SUBTRACT', data, v), has))
        data = tr.combine([attr("mp_pic%d" % (index + i)) for i in range(w)])
        return tr.vmath('ADD', v, tr.vmath('SCALE', tr.vmath('SUBTRACT', data, v, out_w=w), has, out_w=w), out_w=w)

    def group_input(self, key):
        """A function group's parameter socket, fed from where it's called."""
        if key.startswith("P: "):
            return self.scalar(key[3:], self._defaults.get(key, 0.0))
        if key.startswith("V: "):
            return self.vector(key[3:], self._defaults.get(key, (0.0, 0.0, 0.0, 1.0)))[0]
        return self.tr.const(0.0)

    def static_switch(self, name, default):
        return bool(self.entry.get("switches", {}).get(name, default))

    def static_mask(self, name, default):
        """The instance chain's mask, if it states one (None: it doesn't)."""
        m = self.entry.get("masks", {}).get(name)
        return tuple(m) if m else None

    def guess_mask(self, name, default, v):
        """A channel mask the instance doesn't state - cooked instances keep
        no mask choice, it's baked into their shader. When its default channel
        is empty in the one texture behind it and another channel isn't, the
        artist picked that one (Dark Shield's cube mask: R empty, G painted)."""
        name = name or "(unnamed)"
        on = [i for i, b in enumerate(default[:3]) if b]
        sock = getattr(v, "s", None) if v is not None and not v.const else None
        # UV-offset masks shift an effect rather than place it: never guessed
        if len(on) != 1 or not hasattr(sock, "node") or "offset" in name.lower():
            return None
        images = self._images_upstream(sock)
        if len(images) != 1:
            return None
        # from here the choice depends on the texture's pixels: another instance's may differ
        self.reusable = False
        means = self._channel_means(images[0])
        if means is None or means[on[0]] > 0.003:
            return None
        best = max(range(3), key=lambda i: means[i])
        if means[best] < 0.02:
            return None
        # one painted channel places one effect: the first mask reaching it takes it
        # (another effect left on its empty default channel was likely unused)
        claim = (images[0].name, best)
        if self._claimed.setdefault(claim, name) != name:
            return None
        self.note("channel mask %s: the instance's choice isn't in cooked data; %s is empty in %s, %s used" % (
            name.strip(), "RGB"[on[0]], images[0].name, "RGB"[best]))
        return tuple(i == best for i in range(4))

    @staticmethod
    def _images_upstream(sock, limit=400):
        """The images a socket's value comes from, within its tree."""
        seen, found, todo = set(), [], [sock.node]
        while todo and len(seen) < limit:
            n = todo.pop()
            if n.name in seen:
                continue
            seen.add(n.name)
            if n.bl_idname == "ShaderNodeTexImage" and n.image is not None:
                if n.image not in found:
                    found.append(n.image)
                continue
            for i in n.inputs:
                for l in i.links:
                    todo.append(l.from_node)
        return found

    _means = {}

    @classmethod
    def _channel_means(cls, img):
        """R, G, B coverage of an image (a sparse sample), cached."""
        if img.name not in cls._means:
            try:
                import numpy as np
                px = np.empty(len(img.pixels), dtype=np.float32)
                img.pixels.foreach_get(px)
                cls._means[img.name] = tuple(float(x) for x in px.reshape(-1, 4)[::7, :3].mean(axis=0))
            except Exception:
                cls._means[img.name] = None
        return cls._means[img.name]

    def texture_parameter(self, name, default):
        key = self.entry.get("textures", {}).get(name, default)
        self.tex_params.setdefault(key, set()).add(name)
        self.tex_default.setdefault(name, default)
        return key

    def collection(self, name, path=None):
        """A material parameter collection's default for `name`."""
        if not path:
            self.note("collection parameter %s without its collection: 0" % name)
            return self.tr.const(0.0)
        c = self.app.collection(path)
        if name in c.get("scalars", {}):
            return self.tr.const(float(c["scalars"][name]))
        if name in c.get("vectors", {}):
            return self.tr.const(tuple(c["vectors"][name]), 4)
        self.note("collection %s has no %s: 0" % (path.split("/")[-1], name))
        return self.tr.const(0.0)

    # ------------------------------------------------------------ assets
    def function(self, name, objpath=None):
        return self.app.graph(objpath or name)

    def special_function(self, name, inputs):
        return None

    def _record(self, key):
        try:
            return self.app.texture(key)
        except Exception as e:
            self.note("texture %s: %s" % (key.split("/")[-1], e))
            return None

    def _image(self, key, rec, data=None):
        if key in self._images:
            return self._images[key]
        img = None
        if rec is not None:
            img = _load(rec["File"], int(rec.get("Width") or 0), int(rec.get("Height") or 0))
            short = key.rsplit("/", 1)[-1].split(".")[0]
            if not img.name.startswith(short):
                img.name = short
            srgb = rec.get("Srgb") and not rec.get("Hdr")
            if data is not None:
                srgb = srgb and data != "normal"
            space = COLORSPACE_SRGB if srgb else COLORSPACE_DATA
            try:
                # setting it (even to what it is) makes Blender refresh the image
                if img.colorspace_settings.name != space:
                    img.colorspace_settings.name = space
            except TypeError:
                pass
        if img is None:
            img = bpy.data.images.get("MP missing") or bpy.data.images.new("MP missing", 4, 4)
        self._images[key] = img
        return img

    def texture(self, key, sampler):
        normal = "Normal" in str(sampler)
        if normal:
            self.tex_normal.add(key)
        return self._image(key, self._record(key), "normal" if normal else None)

    def cube(self, key):
        self.reusable = False
        self.note("cube texture %s read as a flat image" % key.split("/")[-1])
        return self._image(key, self._record(key))

    def volume(self, key):
        self.reusable = False
        rec = self._record(key)
        img = self._image(key, rec)
        if rec is None:
            return img, 1, 1
        return img, int(rec.get("Width", 1)), int(rec.get("Depth", 1))

    def texture_slices(self, key, sampler):
        """A texture array: the app exports it as a stack of slices (slice 0 on
        top); each becomes an image of its own."""
        self.reusable = False
        rec = self._record(key)
        if rec is None or rec.get("Kind") != "array" or int(rec.get("Depth", 1)) < 2:
            return None
        stack = self._image(key, rec)
        w, h = stack.size
        depth = int(rec["Depth"])
        sh = h // depth
        px = list(stack.pixels[:])
        out = []
        for i in range(depth):
            name = "%s [%d]" % (key.split("/")[-1].split(".")[0], i)
            img = bpy.data.images.get(name) or bpy.data.images.new(name, w, sh, alpha=True, float_buffer=stack.is_float)
            # Blender's pixel rows run bottom up: slice 0 (the top) is the last rows
            top = h - (i + 1) * sh
            img.pixels[:] = px[top * w * 4:(top + sh) * w * 4]
            img.colorspace_settings.name = stack.colorspace_settings.name
            img.pack()
            out.append(img)
        return out
