# Generated by materialporter/tools/sync_fork.py from blender/material_porter/fallback.py - edit it there.
"""A material whose master was cooked without its editor graph (a UEFN
island's own materials ship that way): nothing to translate, so it's built
the way FortnitePorting builds everything - a Principled BSDF fed by the
textures and values, each given a role by its parameter's name (else its
texture's suffix). The textures nothing claims wait in an "Unused Textures"
frame, to wire by hand. The material says it's approximate (mp_fallback)."""
import bpy

# (role, parameter-name fragments), first match wins
_BY_PARAM = (
    ("normal", ("normal",)),
    ("specmasks", ("specularmask", "specmask", "srm")),
    ("orm", ("orm", "occlusionroughness", "aorm")),
    ("roughness", ("roughness",)),
    ("metallic", ("metallic", "metalness")),
    ("emissive", ("emissive", "emission", "glow")),
    ("opacity", ("opacity", "alpha")),
    ("base", ("diffuse", "basecolor", "base color", "albedo", "color", "colour", "texture", "tex", "map")),
)
# (role, texture-name suffixes)
_BY_SUFFIX = (
    ("normal", ("_n", "_normal", "_nrm", "_nor", "_normals")),
    ("specmasks", ("_s", "_srm", "_specularmasks", "_spec")),
    ("orm", ("_orm", "_arm", "_mra", "_rma")),
    ("roughness", ("_r", "_rough", "_roughness")),
    ("metallic", ("_m", "_metal", "_metallic", "_metalness")),
    ("emissive", ("_e", "_emissive", "_emit", "_emission")),
    ("opacity", ("_a", "_alpha", "_opacity", "_mask")),
    ("base", ("_d", "_bc", "_basecolor", "_base_color", "_diffuse", "_albedo", "_col", "_color", "_c", "_diff")),
)
_TINTS = ("color", "basecolor", "base color", "tint", "albedo", "diffusecolor", "diffuse color", "colour")


def _role_of_param(name):
    n = name.lower().replace("_", "")
    for role, frags in _BY_PARAM:
        if any(f.replace("_", "") in n for f in frags):
            return role
    return None


def _role_of_texture(path):
    n = path.rsplit("/", 1)[-1].split(".")[0].lower()
    for role, suffixes in _BY_SUFFIX:
        if any(n.endswith(s) for s in suffixes):
            return role
    return None


def build_fallback(entry, app, objects, env_cls, settings, keys):
    """(material, notes). keys: build's (PREFIX, KEY_PATH, KEY_REV, BUILD_REVISION, KEY_VARIANT)."""
    prefix, key_path, key_rev, revision, key_variant = keys
    mat = bpy.data.materials.new(prefix + entry["name"])
    nt = mat.node_tree
    nt.nodes.clear()
    N, L = nt.nodes, nt.links
    env = env_cls(app, entry, objects)
    s = settings(entry)
    out = N.new("ShaderNodeOutputMaterial")
    out.location = (400, 0)
    bsdf = N.new("ShaderNodeBsdfPrincipled")
    bsdf.location = (100, 0)
    L.new(bsdf.outputs[0], out.inputs["Surface"])

    textures = dict(entry.get("textures") or {})
    scalars = entry.get("scalars") or {}
    vectors = entry.get("vectors") or {}
    roles, unused = {}, []
    for name, path in sorted(textures.items()):
        role = _role_of_param(name) or _role_of_texture(path)
        if role and role not in roles:
            roles[role] = (name, path)
        else:
            unused.append((name, path))
    # the master's own fixed textures: by their names only
    for path in entry.get("referenced_textures") or []:
        if path in textures.values():
            continue
        role = _role_of_texture(path)
        if role and role not in roles:
            roles[role] = (path.rsplit("/", 1)[-1].split(".")[0], path)
        else:
            unused.append((path.rsplit("/", 1)[-1].split(".")[0], path))

    y = [300]

    def image(path, normal=False, label=None):
        n = N.new("ShaderNodeTexImage")
        n.image = env.texture(path, "SAMPLERTYPE_Normal" if normal else "")
        n.label = label or path.rsplit("/", 1)[-1].split(".")[0]
        n.location = (-700, y[0])
        y[0] -= 280
        return n

    def value(names, default=None):
        for k, v in scalars.items():
            if k.lower().replace("_", "") in names:
                return float(v)
        return default

    tint = next((v for k, v in vectors.items() if k.lower() in _TINTS), None)
    base = roles.get("base")
    if tint is None and not base:
        # no texture and no colour by name: a lone colour parameter is the colour ("Param")
        tint = next((v for k, v in sorted(vectors.items())
                     if not any(w in k.lower() for w in ("emissive", "emission", "glow", "fresnel", "rim"))), None)
    if base:
        img = image(base[1], label=base[0])
        col = img.outputs["Color"]
        if tint is not None:
            mix = N.new("ShaderNodeMix")
            mix.data_type = 'RGBA'
            mix.blend_type = 'MULTIPLY'
            mix.inputs["Factor"].default_value = 1.0
            mix.location = (-300, 300)
            L.new(col, mix.inputs["A"])
            mix.inputs["B"].default_value = tuple(tint[:3]) + (1.0,)
            col = mix.outputs["Result"]
        L.new(col, bsdf.inputs["Base Color"])
        if s["blend"] != "BLEND_Opaque" and "opacity" not in roles:
            L.new(img.outputs["Alpha"], bsdf.inputs["Alpha"])
    elif tint is not None:
        bsdf.inputs["Base Color"].default_value = tuple(tint[:3]) + (1.0,)

    def channel(img, i):
        sep = N.new("ShaderNodeSeparateColor")
        sep.location = (img.location[0] + 300, img.location[1])
        L.new(img.outputs["Color"], sep.inputs[0])
        return sep.outputs[i]

    if "normal" in roles:
        img = image(roles["normal"][1], normal=True, label=roles["normal"][0])
        # UE normal maps are DirectX (green down)
        sep = N.new("ShaderNodeSeparateColor")
        sep.location = (-400, img.location[1])
        L.new(img.outputs["Color"], sep.inputs[0])
        inv = N.new("ShaderNodeMath")
        inv.operation = 'SUBTRACT'
        inv.inputs[0].default_value = 1.0
        inv.location = (-250, img.location[1] - 40)
        L.new(sep.outputs[1], inv.inputs[1])
        comb = N.new("ShaderNodeCombineColor")
        comb.location = (-100, img.location[1])
        L.new(sep.outputs[0], comb.inputs[0])
        L.new(inv.outputs[0], comb.inputs[1])
        L.new(sep.outputs[2], comb.inputs[2])
        nm = N.new("ShaderNodeNormalMap")
        nm.location = (-50, img.location[1] - 200)
        L.new(comb.outputs[0], nm.inputs["Color"])
        L.new(nm.outputs[0], bsdf.inputs["Normal"])
    if "specmasks" in roles:
        # Fortnite's SpecularMasks: R specular, G metallic, B roughness
        img = image(roles["specmasks"][1], label=roles["specmasks"][0])
        L.new(channel(img, 0), bsdf.inputs["Specular IOR Level"])
        L.new(channel(img, 1), bsdf.inputs["Metallic"])
        L.new(channel(img, 2), bsdf.inputs["Roughness"])
    elif "orm" in roles:
        img = image(roles["orm"][1], label=roles["orm"][0])
        L.new(channel(img, 1), bsdf.inputs["Roughness"])
        L.new(channel(img, 2), bsdf.inputs["Metallic"])
    else:
        if "roughness" in roles:
            L.new(channel(image(roles["roughness"][1], label=roles["roughness"][0]), 0), bsdf.inputs["Roughness"])
        else:
            bsdf.inputs["Roughness"].default_value = value({"roughness"}, 0.5)
        if "metallic" in roles:
            L.new(channel(image(roles["metallic"][1], label=roles["metallic"][0]), 0), bsdf.inputs["Metallic"])
        else:
            bsdf.inputs["Metallic"].default_value = value({"metallic", "metalness"}, 0.0)
    emissive_col = next((v for k, v in vectors.items() if "emissive" in k.lower() or "emission" in k.lower()), None)
    strength = value({"emissivestrength", "emissiveintensity", "emissive", "emissionstrength", "glow", "brightness"}, 1.0)
    if "emissive" in roles:
        img = image(roles["emissive"][1], label=roles["emissive"][0])
        L.new(img.outputs["Color"], bsdf.inputs["Emission Color"])
        bsdf.inputs["Emission Strength"].default_value = strength
    elif emissive_col is not None and any(emissive_col[:3]):
        bsdf.inputs["Emission Color"].default_value = tuple(emissive_col[:3]) + (1.0,)
        bsdf.inputs["Emission Strength"].default_value = strength
    if "opacity" in roles and s["blend"] != "BLEND_Opaque":
        L.new(channel(image(roles["opacity"][1], label=roles["opacity"][0]), 0), bsdf.inputs["Alpha"])
    elif s["blend"] != "BLEND_Opaque" and not base:
        bsdf.inputs["Alpha"].default_value = value({"opacity", "alpha"}, 1.0)

    if s["blend"] != "BLEND_Opaque":
        mat.surface_render_method = 'BLENDED' if "Masked" not in s["blend"] else 'DITHERED'
    mat.use_backface_culling = not s["two_sided"]

    if unused:
        frame = N.new("NodeFrame")
        frame.label = "Unused Textures"
        frame.location = (-1200, 300)
        yy = 0
        for name, path in unused:
            n = N.new("ShaderNodeTexImage")
            n.image = env.texture(path, "")
            n.label = name
            n.parent = frame
            n.location = (0, yy)
            yy -= 280
    mat[key_path] = entry["path"]
    mat[key_rev] = revision
    mat["mp_fallback"] = 1
    if entry.get("variant"):
        mat[key_variant] = entry["variant"]
    notes = ["approximate: its master has no editor graph (an island's own material), built from %d texture(s) and its values"
             % (len(roles) + len(unused))] + list(env.notes)
    return mat, notes
